src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use DateTimeImmutable;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @Vich\Uploadable
 * @ORM\Entity(repositoryClass=PostRepository::class)
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @Assert\NotBlank(message="Le champ title ne peut pas etre vide")
     * @ORM\Column(type="string", length=255)
     */
    private ?string $title;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @Assert\NotBlank(message="Le champ sommaire ne peut pas etre vide")
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $summary;

    /**
     * @Assert\NotBlank(message="Le champ content ne peut pas etre vide")
     * @ORM\Column(type="text")
     */
    private string $content;

   /**
    * @Vich\UploadableField(mapping="post_image", fileNameProperty="image_name")
    * @var File|null
    */
    private ?File $imageFile = null;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private ?string $image_name;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private ?DateTimeImmutable $created_at;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?DateTimeImmutable $published_at;

    /**
     * @ORM\Column(type="datetime_immutable")
     */
    private ?DateTimeImmutable $updated_at;

    /**
     * @ORM\Column(type="boolean")
     */
    private ?bool $is_published;

    /**
     * @ORM\ManyToMany(targetEntity=Category::class, inversedBy="posts")
     */
    private Collection $categories;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="post", cascade={"remove"})
     */
    private Collection $comments;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="posts")
     */
    private $author;

    public function __construct()
    {
        $this->categories = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function getSummary(): ?string
    {
        return $this->summary;
    }

    public function setSummary(?string $summary): self
    {
        $this->summary = $summary;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return File|null
     */
    public function getImageFile(): ?File
    {
       return $this->imageFile;
    }

    /**
     * @param File|null $imageFile
     * @return Post
     */
    public function setImageFile(?File $imageFile = null): Post
    {
       $this->imageFile = $imageFile;

       if (null !== $imageFile) {
          $this->updated_at = new DateTimeImmutable();
       }

       return $this;
    }

    public function getImageName(): ?string
    {
        return $this->image_name;
    }

    public function setImageName(string $image_name = null): self
    {
        $this->image_name = $image_name;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPublishedAt(): ?DateTimeImmutable
    {
        return $this->published_at;
    }

    public function setPublishedAt(DateTimeImmutable $published_at): self
    {
        $this->published_at = $published_at;

        return $this;
    }

    public function getUpdatedAt(): ?DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(DateTimeImmutable $updated_at): self
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getIsPublished(): ?bool
    {
        return $this->is_published;
    }

    public function setIsPublished(bool $is_published): self
    {
        $this->is_published = $is_published;

        return $this;
    }

    /**
     * @return Collection|Category[]
     */
    public function getCategories(): Collection
    {
        return $this->categories;
    }

    public function addCategory(Category $category): self
    {
        if (!$this->categories->contains($category)) {
            $this->categories[] = $category;
        }

        return $this;
    }

    public function removeCategory(Category $category): self
    {
        $this->categories->removeElement($category);

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }
}

src/Controller/Author/AuthorController.php
<?php

namespace App\Controller\Author;

use App\Entity\Comment;
use App\Entity\Post;
use App\Form\PostType;
use App\Repository\PostRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Contracts\Cache\CacheInterface;

/**
 * @Route("/blog/author")
 */
class AuthorController extends AbstractController
{
    protected $cache;

    public function __construc(CacheInterface $cache)
    {
       $this->cache = $cache;
    }

    /**
     * @Route("/", name="blog_author_index", methods={"GET"})
     */
    public function index(PostRepository $postRepository): Response
    {
        return $this->render('author/index.html.twig', [
            'posts' => $postRepository->findAllDesc(),
        ]);
    }

   /**
    * @Route("/new", name="blog_author_new", methods={"GET", "POST"})
    */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $post = new Post();
        $post->setCreatedAt(new \DateTimeImmutable());
        $post->setUpdatedAt(new \DateTimeImmutable());
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('blog_author_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('author/new.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="blog_author_show", methods={"GET"})
     */
    public function show(Post $post): Response
    {
        return $this->render('author/show.html.twig', [
            'post' => $post,
        ]);
    }

   /**
    * @Route("/{id}/edit", name="blog_author_edit", methods={"GET", "POST"})
    */
    public function edit(Request $request, Post $post, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('blog_author_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('author/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

   /**
    * @Route("/{id}", name="blog_author_delete", methods={"POST"})
    */
    public function delete(Request $request, Post $post, EntityManagerInterface $entityManager, Comment $comment): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('blog_author_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/author/_delete_form.html.twig
<form method="post" action="{{ path('blog_author_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure' +
 ' you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn btn-danger">Delete</button>
</form>

templates/author/_form.html.twig
{{ form_start(form) }}
<div class="row">{{ form_row(form.title) }}</div>
<div class="row">{{ form_row(form.summary) }}</div>
<div class="row">
    <div class="col col-sm">{{ form_row(form.categories) }}</div>
    <div class="col col-sm">{{ form_row(form.imageFile) }}</div>
    <div class="col col-sm">{{ form_row(form.published_at) }}</div>
</div>
<div class="row">{{ form_row(form.is_published) }}</div>
<div class="row">{{ form_row(form.content) }}</div>
<button class="btn btn-success">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/author/_user.html.twig
<div class="top">
    <div class="dropdown">
        <a class="btn btn-secondary" href="#" role="button"
           data-bs-toggle="dropdown" aria-expanded="false">
            <i class="fas fa-user"></i>&nbsp;&nbsp;{{ app.user.name }}
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <li class="drop-login">
                <i class="fas fa-user"></i>
                <p class="login-desc">Logged in as <br> {{ app.user.name }}</p>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li class="drop-logout">
                <a class="dropdown-item" href="{{ path('app_logout') }}">
                    <i class="fas fa-sign-out-alt"></i>&nbsp;&nbsp;Déconnexion
                </a>
            </li>
        </ul>
    </div>
</div>

templates/author/edit.html.twig
{% extends 'base/layout.html.twig' %}

{% block layout_class %}author edit{% endblock %}

{% block title 'Auteur | Edit post' %}

{% block css %}
    {{ parent() }}
    {{ encore_entry_link_tags('author') }}
{% endblock %}

{% block js %}
    {{ parent() }}
    {{ encore_entry_script_tags('author') }}
{% endblock %}

{% block layout %}
<div class="contain">
    {% include 'author/_user.html.twig' %}

    <h1 class="title">Edit Post</h1>

    {{ include('author/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('blog_author_index') }}">back to list</a>

    {{ include('author/_delete_form.html.twig') }}
</div>
{% endblock %}

templates/author/index.html.twig
{% extends 'base/layout.html.twig' %}

{% block layout_class %}author index{% endblock %}

{% block title 'Auteur | Post index' %}

{% block css %}
    {{ parent() }}
    {{ encore_entry_link_tags('author') }}
{% endblock %}

{% block js %}
    {{ parent() }}
    {{ encore_entry_script_tags('author') }}
{% endblock %}

{% block layout %}
<div class="contain">
    {% include 'author/_user.html.twig' %}

    <h1 class="title">Post index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Title</th>
                <th>Image</th>
                <th>Date de publication</th>
                <th>Publication</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for post in posts %}
            <tr>
                <td>{{ post.title }}</td>
                <td>
                    <img src="{{ vich_uploader_asset(post, 'imageFile') }}" alt="{{ post.imageName }}" width="75">
                </td>
                <td>{{ post.publishedAt ? post.publishedAt|date('j F Y') : '' }}</td>
                <td>{{ post.isPublished ? 'Publié' : 'Non publié' }}</td>
                <td>
                    <a class="btn btn-sm btn-secondary" href="{{ path('blog_author_show', {'id': post.id}) }}">show</a>
                    <a class="btn btn-sm btn-info" href="{{ path('blog_author_edit', {'id': post.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('blog_author_new') }}">Create new</a>
</div>
{% endblock %}

templates/author/new.html.twig
{% extends 'base/layout.html.twig' %}

{% block layout_class %}author new{% endblock %}

{% block title 'Auteur | New post' %}

{% block css %}
    {{ parent() }}
    {{ encore_entry_link_tags('author') }}
{% endblock %}

{% block js %}
    {{ parent() }}
    {{ encore_entry_script_tags('author') }}
{% endblock %}

{% block layout %}
<div class="contain">
    {% include 'author/_user.html.twig' %}

    <h1 class="title">Create new Post</h1>

    {{ include('author/_form.html.twig') }}

    <a href="{{ path('blog_author_index') }}">back to list</a>
</div>
{% endblock %}

templates/author/show.html.twig
{% extends 'base/layout.html.twig' %}

{% block layout_class %}author show{% endblock %}

{% block title 'Auteur | Post show' %}

{% block layout %}
<div class="contain">
    {% include 'author/_user.html.twig' %}

    <h1 class="title">{{ post.title }}</h1>

    <div class="article">
        <div class="img-card">
            <img src="{{ vich_uploader_asset(post, 'imageFile') }}" alt="{{ post.imageName }}">
        </div>
        <p class="summary">{{ post.summary }}</p>
        <div class="date">
            <em>Date de creation : {{ post.createdAt ? post.createdAt|date('j F Y') : '' }}</em> <br>
            <em>Date de publication : {{ post.publishedAt ? post.publishedAt|date('j F Y') : '' }}</em> <br>
            <em>Dérnier modification : {{ post.updatedAt ? post.updatedAt|date('j F Y') : '' }}</em>
        </div>
        <div class="published">Publication : {{ post.isPublished ? 'publié' : 'non publié' }}</div>
        <article>{{ post.content | raw }}</article>
    </div>

    <a class="btn btn-dark" href="{{ path('blog_author_index') }}">back to list</a>

    <a class="btn btn-info" href="{{ path('blog_author_edit', {'id': post.id}) }}">edit</a>

    {{ include('author/_delete_form.html.twig') }}
</div>
{% endblock %}